### ISSUE TITLE
Super High GPU Usage

### ISSUE THREAD

**Issue by NightmareDreemurr** [kuroni/bongocat-osu#94]
just literally wtf
![image](https://user-images.githubusercontent.com/59122229/97727681-a6164680-1b0b-11eb-89a1-d04baf039813.png)

**Comment by NightmareDreemurr** [comment]
Using 	
CPU

	Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

	Base speed:	3.60 GHz
	Sockets:	1
	Cores:	8
	Logical processors:	16
	Virtualization:	Enabled
	L1 cache:	512 KB
	L2 cache:	2.0 MB
	L3 cache:	16.0 MB

	Utilization	35%
	Speed	4.79 GHz
	Up time	0:02:27:46
	Processes	357
	Threads	5475
	Handles	166604


GPU 1

	NVIDIA GeForce RTX 2080 Ti

	Driver version:	27.21.14.5206
	Driver date:	8/12/2020
	DirectX version:	12 (FL 12.1)
	Physical location:	PCI bus 1, device 0, function 0

	Utilization	62%
	Dedicated GPU memory	3.3/11.0 GB
	Shared GPU memory	0.2/15.9 GB
	GPU Memory	3.5/26.9 GB

IDK why a program that shows key overlays using maybe live2d can eat up so much resource
PLS FIX IT THANKS

**Comment by kuroni** [comment]
Can you try the latest release? A similar problem is fixed some time ago

**Comment by NightmareDreemurr** [comment]
![Uploading image.png…]()
Actually, I downloaded the latest release, it didn't fix and I thought I've used the latest release already

**Comment by kuroni** [comment]
If it is possible, can you check the FPS of the program? It's really odd because I don't have the same issue on my end.

**Comment by NightmareDreemurr** [comment]
![image](https://user-images.githubusercontent.com/59122229/97781063-c73a6e00-1bc3-11eb-8f60-e9a3ad33e64e.png)
It's approximately 2,000 ~ 3,000 frames per second counted by steam overlay

**Comment by kuroni** [comment]
Yeah ... that should not happen. I guess the reason is the ForceVSync function doesn't work as intended.

I will manually set the FPS to 60 then.

**Comment by NightmareDreemurr** [comment]
Thanks for your great work!
I will wait patiently for the next update.

**Comment by kuroni** [comment]
May you try the latest release?

Sorry I have been inactive for quite a while.

**Comment by NightmareDreemurr** [comment]
ok but I'll try it at Dec.31, I'm currently in school without bringing my laptop
Thanks for updating

**Comment by NightmareDreemurr** [comment]
OK That worked pretty well 
![image](https://user-images.githubusercontent.com/59122229/103457951-51559e80-4cfb-11eb-8889-2c909b595e4d.png)
Thanks for your great work!
